### ISSUE TITLE
Cannot access 'androidx.lifecycle.FullLifecycleObserver'

### ISSUE THREAD

**Issue by nicemak** [skydoves/PowerMenu#106]
**Please complete the following information:**
- Library Version [e.g. v2.2.3]
 
**Describe the Bug:**

Android studio shows error on setOnMenuItemClickListener

Cannot access 'androidx.lifecycle.FullLifecycleObserver' which is a supertype of 'com.skydoves.powermenu.AbstractPowerMenu'. Check your module classpath for missing

how to solve this issue?

**Comment by nicemak** [comment]
@skydoves ?

**Comment by nicemak** [comment]
@skydoves any help?

**Comment by skydoves** [comment]
@nicemak Would you add the dependency below to your project?

```gradle
implementation("androidx.lifecycle:lifecycle-common-java8:2.6.1")

```

**Comment by skydoves** [comment]
A new version 1.2.7 has been released. if you still face the issue, you should use the lifecycle version at least 2.6.0 by force. Thanks for reporting this issue!

**Comment by nicemak** [comment]
@skydoves nothing happened, I have already implemented `implementation "androidx.lifecycle:lifecycle-common-java8:2.6.1"`, I changed it back to 2.6.0 but nothing changes. what to do now?

**Comment by RobbWatershed** [comment]
Same here - I still have that error showing up everywhere I use `PowerMenu` even though I've included `implementation("androidx.lifecycle:lifecycle-common-java8:2.6.1")`

I won't lie - this is getting super annoying to see these red lines on my IDE. Is there anything you can do @skydoves ?

**Comment by RobbWatershed** [comment]
bump? 😅

**Comment by TY235** [comment]
You have to ensure that all your modules' `build.gradle` files implement `implementation("androidx.lifecycle:lifecycle-common-java8:2.6.1")`, not just your app-level `build.gradle` file.

**Comment by RobbWatershed** [comment]
After all this time, someone has a working fix!! You're my hero @TY235 😍

**Comment by fobos531** [comment]
> You have to ensure that all your modules' `build.gradle` files implement `implementation("androidx.lifecycle:lifecycle-common-java8:2.6.1")`, not just your app-level `build.gradle` file.

Hello @TY235 how would I do this if I am developing a gradle library myself that just wraps this one?. I am getting this same error when I try to use `showAsDropDown`.

this is what I have in dependencies in my build.gradle:

 implementation ("com.github.skydoves:powermenu:2.2.4")


 def lifecycleVersion = "2.6.1"
implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycleVersion"
implementation "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycleVersion"
implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycleVersion"
implementation("androidx.lifecycle:lifecycle-common-java8:$lifecycleVersion")

But I'm still getting this error in my sample project. 

I dont think I can add the implementation to all my "modules", since I do not directly "control" these modules, they are from 3rd party libraries.
